import type { InterestOption, Session, Speaker } from "@/types";

export const INTEREST_OPTIONS: InterestOption[] = [
  { key: "agents", label: "Agents" },
  { key: "coding", label: "Coding" },
  { key: "evals", label: "Evals" },
  { key: "infrastructure", label: "Infrastructure" },
  { key: "design", label: "Design" },
  { key: "open-models", label: "Open models" },
  { key: "robotics", label: "Robotics" },
  { key: "singapore-ai", label: "Singapore AI" },
  { key: "research", label: "Research" },
  { key: "student-builders", label: "Student builders" },
];

const speaker = (
  name: string,
  company: string,
  title: string,
  bio: string,
  _tags: string[] = [],
): Speaker => {
  void _tags;
  return {
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
    name,
    company,
    title,
    bio,
  };
};

export const fallbackSpeakers: Speaker[] = [
  speaker(
    "Max Buckley",
    "Exa AI",
    "Research engineer",
    "Works on AI-native search and research agents that retrieve, verify, and reason over web-scale information.",
    ["research agents", "search", "evidence"],
  ),
  speaker(
    "Yuntong Zhang",
    "Sonar",
    "Research Consultant",
    "Builds and evaluates coding agents for software engineering, including AutoCodeRover and c-CRAB style review benchmarks.",
    ["coding agents", "evals", "code quality"],
  ),
  speaker(
    "Vedran Jukic",
    "Daytona",
    "Co-founder & CTO",
    "Builds sandbox infrastructure for secure, stateful agent runtime environments.",
    ["agent safety", "sandboxes", "developer tools"],
  ),
  speaker(
    "Vaishant Kameswaran",
    "Greptile",
    "Co-founder",
    "Works on AI code review at scale, including large-volume PR analysis and review quality patterns.",
    ["coding agents", "code review", "evals"],
  ),
  speaker(
    "Rohan S Kumar",
    "Greptile",
    "Co-founder",
    "Works on AI review systems for large engineering teams and agent-written pull requests.",
    ["coding agents", "code review", "evals"],
  ),
  speaker(
    "Thibault Sottiaux",
    "OpenAI",
    "Product and engineering",
    "Works on Codex and computer work agents for software engineering workflows.",
    ["coding agents", "developer tools", "Codex"],
  ),
  speaker(
    "Gabriel Chua",
    "OpenAI",
    "Engineer",
    "Builds with Codex and agentic software engineering systems.",
    ["coding agents", "developer tools", "Codex"],
  ),
  speaker(
    "Dr Feng Yuzhang",
    "GovTech Singapore",
    "Head of AI Practice & Director of AI Programme",
    "Leads AI adoption and AI-first capability building across Singapore public service.",
    ["Singapore AI", "government", "public service"],
  ),
  speaker(
    "Jimmy Lai",
    "Vercel",
    "Director, Next.js",
    "Leads Next.js and works on developer experience for modern AI-native web applications.",
    ["developer tools", "web", "Vercel"],
  ),
  speaker(
    "Annie Luo",
    "Google",
    "UX Researcher",
    "Studies AI-native shopping and image generation interfaces, with a focus on friction and subjective decisions.",
    ["design", "human agency", "UX"],
  ),
  speaker(
    "Jay Demetillo",
    "Canva",
    "Design leader",
    "Works across design systems, creative tools, and AI-assisted creation workflows.",
    ["design", "creative tools", "human agency"],
  ),
  speaker(
    "Eugene Cheah",
    "Featherless",
    "Founder",
    "Builds accessible inference infrastructure and works on efficient open model ecosystems.",
    ["Singapore AI", "inference", "student builders"],
  ),
];

export const fallbackSessions: Session[] = [
  {
    id: "sat-nanoclaw-agent-factory",
    title: "NanoClaw's agent factory: how autonomous NanoClaw agents triage, review, and test every pull request",
    description:
      "Architecture for autonomous PR agents with hard isolation boundaries, zero-trust credential separation, and human approval gates.",
    startsAt: "2026-05-16T09:00:00+08:00",
    endsAt: "2026-05-16T09:15:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [speaker("Gavriel Cohen", "NanoCo, creators of NanoClaw", "CEO", "Creator of NanoClaw, an open-source autonomous agent framework.", ["coding agents", "security"])],
    tags: ["agents", "coding agents", "agent safety", "software"],
    companyNames: ["NanoCo", "NanoClaw"],
  },
  {
    id: "sat-openai-codex",
    title: "Codex for Everyone: From Coding Agent to Computer Work Agent",
    description:
      "How Codex-style software agents expand from coding workflows into broader computer work.",
    startsAt: "2026-05-16T09:18:00+08:00",
    endsAt: "2026-05-16T09:38:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[5]],
    tags: ["agents", "coding agents", "developer tools", "OpenAI", "Codex"],
    companyNames: ["OpenAI"],
  },
  {
    id: "sat-govtech-transformation",
    title: "From Pilot to Platform: How Singapore Is driving AI Transformation in Government",
    description:
      "GovTech Singapore's approach to moving AI from pilots to public-service platforms and agency-wide adoption.",
    startsAt: "2026-05-16T09:41:00+08:00",
    endsAt: "2026-05-16T09:56:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[7]],
    tags: ["Singapore AI", "government", "public service", "platform"],
    companyNames: ["GovTech Singapore"],
  },
  {
    id: "sat-exa-research-agents",
    title: "Research agents beyond retrieval: AI-native search for evidence-heavy work",
    description:
      "How search and agent workflows can help builders navigate contradictory evidence, fast-moving domains, and source quality.",
    startsAt: "2026-05-16T10:25:00+08:00",
    endsAt: "2026-05-16T10:35:00+08:00",
    day: "2026-05-16",
    room: "Hallway signal",
    format: "conversation",
    speakers: [fallbackSpeakers[0]],
    tags: ["research agents", "search", "evidence", "AI for science"],
    companyNames: ["Exa AI"],
  },
  {
    id: "sat-vercel-ship-next",
    title: "Ship what's next",
    description:
      "Modern web frameworks, developer experience, and the product surface around AI-native software.",
    startsAt: "2026-05-16T10:40:00+08:00",
    endsAt: "2026-05-16T11:00:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[8]],
    tags: ["developer tools", "Vercel", "workflow", "web"],
    companyNames: ["Vercel"],
  },
  {
    id: "sat-daytona-sandboxes",
    title: "Why Sandboxes Are Non-Negotiable for Autonomous AI Agents",
    description:
      "Why agents with shell, filesystem, and network access need isolation-first architecture and secrets boundaries.",
    startsAt: "2026-05-16T11:03:00+08:00",
    endsAt: "2026-05-16T11:13:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[2]],
    tags: ["agents", "coding agents", "sandbox", "security", "zero-trust"],
    companyNames: ["Daytona"],
  },
  {
    id: "sat-greptile-prs",
    title: "What We Learned From Analyzing Five Million Vibecoded PRs",
    description:
      "What high-volume AI code review reveals about agent-written code quality, failure modes, and human review gaps.",
    startsAt: "2026-05-16T11:16:00+08:00",
    endsAt: "2026-05-16T11:26:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[3], fallbackSpeakers[4]],
    tags: ["agents", "coding agents", "code review", "evals", "quality"],
    companyNames: ["Greptile"],
  },
  {
    id: "sat-sonar-code-quality",
    title: "AI Agents in Your Code Quality Pipeline: Shipping, Securing, and Measuring Them",
    description:
      "How Sonar ships coding agents into code quality workflows, including security hardening and benchmark-driven review measurement.",
    startsAt: "2026-05-16T11:29:00+08:00",
    endsAt: "2026-05-16T11:39:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[1]],
    tags: ["agents", "coding agents", "evals", "security", "code quality"],
    companyNames: ["Sonar"],
  },
  {
    id: "sat-featherless-inference",
    title: "Inference access for the next wave of builders",
    description:
      "A Singapore builder lens on accessible model inference, open models, and lower-cost experimentation.",
    startsAt: "2026-05-16T11:42:00+08:00",
    endsAt: "2026-05-16T11:52:00+08:00",
    day: "2026-05-16",
    room: "Main stage",
    format: "talk",
    speakers: [fallbackSpeakers[11]],
    tags: ["Singapore AI", "student builders", "inference", "developer tools"],
    companyNames: ["Featherless"],
  },
];
